version: '2.3'

services:

  docker_sdk:
    image: gluoncv_semantic_segmentation_docker_sdk_api:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../datasets:/datasets
      - ../checkpoints:/checkpoints
      - ../classifiers:/classifiers
      - ../docker_sdk_api:/docker_sdk_api
      - ../training_api:/training_api

  user_inteface:
    image: gluoncv_semantic_segmentation_gui:latest
    ports:
      - "4200:80"

  inference_api:
    image: gluoncv_semantic_segmentation_inference_api_gpu:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "4343:4343"
    volumes:
      - ../inference_api/models:/models
      - ../inference_api/models_hash:/models_hash